env:
    # RECOVERY REPOSITORY SOURCE TWRP,PBRP,SHRP
    MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1

    # Config
    CONFIG: config.sh

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 20G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/mastersenpai0405/recovery-ci-builder/twrp-builder/scripts/checks.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/mastersenpai0405/recovery-ci-builder/twrp-builder/scripts/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/mastersenpai0405/recovery-ci-builder/twrp-builder/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/mastersenpai0405/recovery-ci-builder/twrp-builder/scripts/upload.sh | bash
